name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📅 Checkout do repositório
        uses: actions/checkout@v3

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🔧 Build do projeto
        run: npm run build

      - name: ✨ Deploy para o Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel deploy --prod --confirm --token $VERCEL_TOKEN
